config/routes.rb
require "resque_web"

Rails.application.routes.draw do

  mount ResqueWeb::Engine => "/resque_web"

  resources :workers

end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_one :next_worker, class_name: 'Worker', foreign_key: 'next_worker'

  def work(unique_id)
    Kernel.sleep(duration)
    unless work_cmd.nil?
      Kernel.system(work_cmd)
    end
    return if next_worker.nil?

    logger.info("name: #{next_worker_name} state: enqueued unique_id: #{unique_id}")

    WorkJob.set(queue: next_worker_name).perform_later(unique_id)
  end

  def next_worker_id
    if next_worker.nil?
      nil
    else
      next_worker.id
    end
  end

  def next_worker_name
    if next_worker.nil?
      nil
    else
      next_worker.name
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        nw = Worker.find(params[:worker][:next_worker])
        @worker.next_worker = nw
        @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :duration)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FullStackKanban</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :next %><br>
    <%= f.collection_select :next_worker, Worker.order(:name), :id, :name, include_blank: true, selected: @worker.next_worker_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Next</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.duration %></td>
        <td><%= worker.next_worker_name %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @worker.duration %>
</p>

<p>
  <strong>Next:</strong>
  <%= @worker.next_worker_name %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>